server:
  port: 8001

dubbo:
  application:
  ##### 注册服务的名称
    name: order
  ##### 注册中心地址
  registry:
    address: zookeeper://127.0.0.1:2181
  ##### 调用服务超时时间
  consumer:
    timeout: 5000
    check: false